name: Sameer Khanal
subname: I am a Web Developer
description: Hello! My name is Sameer Khanal. I am a freelancer, web developer and software developer. I custom code websites and program games.
url: "https://khanalsameer.com.np"
include:
  - _redirects